local LinearLayout = luajava.bindClass("android.widget.LinearLayout")
local TextView = luajava.bindClass("android.widget.TextView")
local GradientDrawable = luajava.bindClass("android.graphics.drawable.GradientDrawable")
local ViewGroup = luajava.bindClass("android.view.ViewGroup")
local Color = luajava.bindClass("android.graphics.Color")
local context = categoryContainer:getContext()
categoryContainer:removeAllViews()
categoryContainer:setOrientation(LinearLayout.HORIZONTAL)
local categories = {"校园", "萌作", "猎奇", "治愈"}
for i, name in ipairs(categories) do
    local tv = luajava.new(TextView, context)
    tv:setText(name)
    tv:setTextSize(13)
    tv:setTextColor(0xFF333333)
    tv:setPadding(40, 20, 40, 20)
    local bg = luajava.new(GradientDrawable)
    bg:setShape(GradientDrawable.RECTANGLE)
    bg:setCornerRadius(40)
    bg:setColor(0xFFFCE4EC)
    bg:setStroke(2, 0xFFFF4081)
    tv:setBackground(bg)
    tv:setTextColor(0xFFFF4081)
    local params = luajava.new(ViewGroup.MarginLayoutParams, LinearLayout.LayoutParams.WRAP_CONTENT, LinearLayout.LayoutParams.WRAP_CONTENT)
    params.rightMargin = 24
    tv:setLayoutParams(params)
    tv:setOnClickListener(luajava.createProxy("android.view.View$OnClickListener", {
        onClick = function(v)
            toast("搜索: " .. name)
        end
    }))
    categoryContainer:addView(tv)
end
categoryContainer:requestLayout()
local LinearLayout = luajava.bindClass("android.widget.LinearLayout")
local EditText = luajava.bindClass("android.widget.EditText")
local Button = luajava.bindClass("android.widget.Button")
local LayoutParams = luajava.bindClass("android.widget.LinearLayout$LayoutParams")
local GradientDrawable = luajava.bindClass("android.graphics.drawable.GradientDrawable")
searchContainer:removeAllViews()
searchContainer:setOrientation(LinearLayout.HORIZONTAL)
searchContainer:setWeightSum(1)
searchContainer:setGravity(LinearLayout.VERTICAL)
local function createRoundBg(radius, bgColor, strokeW, strokeColor)
    local drawable = luajava.new(GradientDrawable)
    drawable:setShape(GradientDrawable.RECTANGLE)
    drawable:setCornerRadius(radius)
    drawable:setColor(bgColor)
    if strokeW and strokeColor then
        drawable:setStroke(strokeW, strokeColor)
    end
    return drawable
end
local etSearch = luajava.new(EditText, activity)
etSearch:setHint("搜索...")
etSearch:setTextSize(14)
etSearch:setTextColor(color("#333333"))
etSearch:setHintTextColor(color("#AAAAAA"))
etSearch:setBackground(nil)
local etRadius = dp(20)
local etBg = createRoundBg(etRadius, color("#FFFFFF"), dp(1), color("#E0E0E0"))
etSearch:setBackground(etBg)
etSearch:setPadding(dp(16), 0, dp(16), 0)
local etParams = luajava.new(LayoutParams, 0, dp(40), 1)
etParams:setMargins(0, 0, dp(8), 0)
etSearch:setLayoutParams(etParams)
local btnSearch = luajava.new(Button, activity)
btnSearch:setText("搜索")
btnSearch:setTextSize(14)
btnSearch:setTextColor(color("#FFFFFF"))
btnSearch:setBackground(nil)
local btnRadius = dp(20)
local btnBg = createRoundBg(btnRadius, color("#FF4081"), 0, 0)
btnSearch:setBackground(btnBg)
local btnParams = luajava.new(LayoutParams, dp(64), dp(40))
btnSearch:setLayoutParams(btnParams)
searchContainer:addView(etSearch)
searchContainer:addView(btnSearch)
searchContainer:requestLayout()
searchContainer:invalidate()
btnSearch:setOnClickListener(luajava.createProxy("android.view.View$OnClickListener", {
    onClick = function(v)
        local keyword = etSearch:getText():toString()
        if keyword ~= "" then
            toast("搜索: " .. keyword)
        else
            toast("请输入搜索内容")
        end
    end
}))
